#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Repo Dispatcher

on: 
  # push: 
  #   branches:
  #     - master
  schedule:
    - cron: 30 13 * * *
  workflow_dispatch:
    inputs:
      skip:
        description: 'Skip version check'
        required: false
        default: 'true'

env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
    - name: cancel running workflows
      uses: styfle/cancel-workflow-action@main
      with:
        workflow_id: 4439867
        access_token: ${{ github.token }}

    - name: Trigger Compile
      run: |
        sudo timedatectl set-timezone "$TZ"
        if [[ "${{ github.event.inputs.skip }}" == 'true' ]]; then
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "x86_64 ${{ env.SSH }}", "client_payload": {"target": "x86_64"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "nanopi-r2s ${{ env.SSH }}", "client_payload": {"target": "nanopi-r2s"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "nanopi-r4s ${{ env.SSH }}", "client_payload": {"target": "nanopi-r4s"}}'
        else
          kernel_r=$(curl -s https://op.supes.top/firmware/x86_64/version.txt | tr "\r\n" "," | cut -f 3 -d ,)
          kernel_l=$(curl -s https://raw.githubusercontent.com/openwrt/openwrt/master/include/kernel-version.mk | grep LINUX_KERNEL_HASH-5.10* | cut -f 3 -d ' ')
            if [ $kernel_r != $kernel_l ]; then
              curl \
              -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
              -H "Accept: application/vnd.github.everest-preview+json" \
              -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
              -d '{"event_type": "x86_64 ${{ env.SSH }}", "client_payload": {"target": "x86_64"}}'
            fi
          kernel_r=$(curl -s https://op.supes.top/firmware/nanopi-r2s/version.txt | tr "\r\n" "," | cut -f 3 -d ,)
          kernel_l=$(curl -s https://raw.githubusercontent.com/immortalwrt/immortalwrt/master/include/kernel-version.mk | grep LINUX_KERNEL_HASH-5.10* | cut -f 3 -d ' ')
            if [ $kernel_r != $kernel_l ]; then
              curl \
              -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
              -H "Accept: application/vnd.github.everest-preview+json" \
              -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
              -d '{"event_type": "nanopi-r2s ${{ env.SSH }}", "client_payload": {"target": "nanopi-r2s"}}'
              curl \
              -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
              -H "Accept: application/vnd.github.everest-preview+json" \
              -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
              -d '{"event_type": "nanopi-r4s ${{ env.SSH }}", "client_payload": {"target": "nanopi-r4s"}}'
            fi
        fi

